### ISSUE TITLE
dmarc rua with size ("!10m") not recognized

### ISSUE THREAD

**Issue by mjl-** [wttw/aboutmyemail#37]
See https://aboutmy.email/5715f57/dmarc. The rua is `mailto:dmarc-reports@beta.gopherwatch.org!10m`. The `!10m` is the max report size. The error message for the hover over "Error" is "No MX found for beta.gopherwatch.org!10m".

See "dmarc-uri" in https://datatracker.ietf.org/doc/html/rfc7489#section-6.4, and a few examples with "!10m" in the same document.

**Comment by wttw** [comment]
Ta. I'll fix that.

**Comment by wttw** [comment]
Fixed in v0.9.15.
