### ISSUE TITLE
Incorrect BIMI error with a=

### ISSUE THREAD

**Issue by Dreamsorcerer** [wttw/aboutmyemail#44]
> If present, this tag MUST have an empty value or ...
https://datatracker.ietf.org/doc/html/draft-brand-indicators-for-message-identification-05#name-assertion-record-definition

But, the report here shows:
![image](https://github.com/wttw/aboutmyemail/assets/2203121/7cc3363a-bbae-4f3d-ad4a-900699287fb8)

**Comment by wttw** [comment]
Should be fixed in 0.9.19.
