### ISSUE TITLE
Menu breaks when window is smaller than 1024px

### ISSUE THREAD

**Issue by joelbeckham** [wttw/aboutmyemail#9]
Hey! Thanks for your work on this tool. It's awesome!

In Chrome, when the window size is smaller than 1024px the menu collapses down, but then doesn't expand correctly when you click the hamburger menu. It expands, but into a tiny scrollable area at the top.

![image](https://github.com/wttw/aboutmyemail/assets/10885194/3048d323-2376-4ca1-a26a-e98942d9223d)

**Comment by wttw** [comment]
CSS, we hates it.

I'll poke at this soon, once I've got some of the more breaking backend bugs fixed.

**Comment by joelbeckham** [comment]
The CSS outsmarts me every time, so I understand. 😁 

No big rush on this. It's definitely not blocking -- I can just not use small windows.

**Comment by wttw** [comment]
Seems to work for me (Chrome, MacOS, production website). It's possible I fixed it accidentally while fixing somehting else, but I can't replicate.

If you still see issues, reopen this ticket and I'll take another look. An example URL that fails and what OS you're running Chrome on would be useful
